### ISSUE TITLE
[DOCS] 트다 서비스에 CI/CD 적용하기😭

### ISSUE THREAD

**Issue by sumin-dev** [TrainingDiary/training-diary-frontend#6]
### 📝 개요
트다(트레이닝 다이어리) 서비스에 CI/CD를 도입하기까지 많은 과정이 있었습니다.
**CI/CD를 도입하게 된 배경**과 CI/CD의 **개념 및 사용법, 트러블슈팅**에 대해 소개하겠습니다 🤓
 
### 📍 CICD란?
- 개발자가 사용자들에게 서비스를 배포하기까지는 개발, 테스트, 빌드, 배포 등의 많은 과정이 필요합니다.
- 이러한 과정은 추가 기능 개발이나 예상 못한 오류 수정 등으로 코드의 변경이 있을 때마다 반복됩니다.
- `CI/CD`는 이런 과정들을 자동화하여 애플리케이션을 짧은 주기로 사용자들에게 제공하고
- 개발자들이 빌드, 배포와 같은 작업에 투자하는 시간을 단축시켜 개발에 더 많은 시간을 투자할 수 있게 해줍니다.
- `CI`는 `Continuous Integration`의 약자로, 지속적인 통합이라는 의미입니다. 
- 새로운 코드 변경 사항이 정기적으로 빌드 및 테스트되어 공유 레포지토리에 통합하는 것입니다.
- `CD`는 `Continuous Delivery` 혹은 `Continuous Deployment`의 약자로, 지속적인 서비스 제공 혹은 지속적인 배포라는 의미입니다.
- 개발자의 변경 사항이 레포지토리를 넘어, 사용자의 프로덕션 환경까지 릴리즈 되는 것을 의미합니다.

### 📍 CI/CD를 도입하게 된 배경
- 트다 FE팀은 배포 채널로 Netlify를 선택했습니다. Netlify가 대역폭 제한을 100G까지 무료로 제공하기 때문입니다!
- 사진과 동영상을 많이 다루는 서비스 특성상, 50G 무료제공하는 Vercel보다 2배나 많은 Netlify가 더 적합하다고 생각했습니다.
- Netlify든 Vercel이든 클라이언트 배포 채널은 기본적으로 자동 배포(`CD`)를 지원합니다.
- Git 레포지토리와 통합되어 특정 브랜치에 변경사항이 생길 때마다 자동으로 사이트를 빌드하고 배포해 줄 수 있습니다.
- 다만, 배포과정에 세밀한 단계를 추가할 수 없습니다. 
- 저희가 원하는 배포단계는 `master브랜치로 변경사항 반영` -> `테스트코드 통과` -> `빌드` -> `배포`인데,
- 테스트코드를 검증하는 단계가 없어서 외부 CI/CD 도구를 사용해 테스트가 성공적으로 완료된 경우에만 배포하도록 했습니다.

### 📍 CI/CD 도구: GitHub Actions
- 트다 FE팀은 CI/CD 도구로 GitHub Actions를 선택했습니다.
- GitHub에서 제공하는 무료 툴로, 레포지토리와 통합되어 있어서 GitHub 이벤트에 반응하는 워크플로우를 쉽게 설정할 수 있습니다.

> 여기서 생긴 문제점! 🧐
> Netlify도 자동배포를 지원하고, GitHub Actions도 사용하면 빌드 & 배포 과정이 충돌하는 거 아냐?

### 📍 트러블 슈팅
**1. 잘못된 workflow**
- 아래는 GitHub Actions를 사용하기 위해 작성한 workflow 파일입니다
- 제가 원했던 흐름은 GitHub Actions에서 테스트코드까지 검증 후, Netlify를 통해 빌드 및 배포하는 순서였는데,
- master 브랜치에 변경사항이 생기는 즉시, 2개가 동시에 독립적으로 돌아가기 시작했습니다.
- 심지어는 GitHub Actions에서 테스트 코드가 실패했는데, Netlify에서는 이미 배포까지 끝내고 기다리고 있었습니다.
```
// deploy.yml

name: Deploy to Netlify

on:
  push:
    branches:
      - master

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Run tests
        run: npm test
```

**2. 바뀌는 production url**
- workflow 파일에 Netlify 배포하는 코드를 추가했습니다.
- Netlify에서 NETLIFY_AUTH_TOKEN과 NETLIFY_SITE_ID를 발급받고, GitHub에 secret으로 등록했습니다.
- workflow 작성법은 [Marketplace의 Netlify Actions](https://github.com/marketplace/actions/netlify-actions)를 참고했습니다.
- Netlify 사이트에서는 자동배포가 실행되면 안되니, `Lock to stop auto publishing` 기능을 이용해 자동배포를 멈췄습니다.

```
// deploy.yml
// Run test 아래에 추가

      - name: Build project
        run: npm run build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './dist'
          production-branch: master
          deploy-message: 'Deploy from GitHub Actions'
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
```
- GitHub Actions 로그를 확인해보니 테스트코드 잘 동작하고, 빌드하고, 배포했습니다.
- 문제는 Netlify에 설정해놓은 production url이 아닌 다른 URL로 배포가 되었습니다.
- 자동배포를 꺼놓은 Production url은 변경사항이 반영되지 않은 채 예전의 형태를 유지하고 있었고,
- 새로운 임시 URL이 만들어졌습니다. 임시 URL은 Netlify가 새로운 배포를 테스트하기 위해 프리뷰 용도로 만든 URL이라고 합니다.
- <img width="970" alt="image" src="https://github.com/TrainingDiary/training-diary-frontend/assets/109029407/ddc03553-d430-4782-973d-51f9a8929c1f">

**3. production URL에 배포하기**
- Netlify 사이트의 `Lock to stop auto publishing` 기능을 다시 원복하여 자동배포를 설정해두고,
- 트다 서비스의 프론트엔드 repository 연결을 끊었습니다.
- 배포 채널은 Netlify를 쓰지만, 특정 브랜치의 변경사항을 통해 자동배포하는 기능은 사용되지 않도록 하면서
- production URL에 배포되는 즉시 반영될 수 있도록 설정했습니다. 성공적으로 배포 완료! 🎉
 <img width="1114" alt="image" src="https://github.com/TrainingDiary/training-diary-frontend/assets/109029407/78a3598e-fa99-47ec-9838-fd1b13cb4c9c">

- 되는 경우의 수를 찾기 위한 수많은 배포테스트 😭
 <img width="1153" alt="image" src="https://github.com/TrainingDiary/training-diary-frontend/assets/109029407/875961ec-2af8-4ebc-9e82-d14a762dea97">

### 📍 GitHub Actions workflow 코드 설명
```
// 프로젝트 폴더에 .github/workflows/deploy.yml 파일 만들기

// workflow의 이름. 해당 값으로 Slack 연동 등 다양한 곳에서 사용 가능
name: Deploy to Netlify

// workflow를 동작하게 하는 trigger.
// repository의 master 브랜치에 push 이벤트가 발생할 때마다 실행
on:
  push:
    branches:
      - master

// workflow 기술
jobs:
  // job의 이름
  test-and-deploy:
    // 해당 job을 리눅스 환경에서 사용
    runs-on: ubuntu-latest

   // 다른 사람이 만들어놓은 action을 사용하여 step안의 일련의 과정 실행
    steps:
      // 해당 프로젝트를 리눅스 환경에 checkout
      - name: Checkout code
        uses: actions/checkout@v4

      // 해당 환경을 Node.js에서 실행 (노드 버전은 20)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      // push할 때마다 npm install을 하지않고
      // 해당 프로젝트의 node_monules가 변했을 때만 npm install
      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}

      // 위에서 검사한 node_modules cache 검사를 바탕으로
      // cache-hit가 아닐 때만 npm install
      // cache-hit가 true라면 해당 step 건너뛰기
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      // 테스트 코드 실행
      - name: Run tests
        run: npm test

      // 프로젝트 빌드
      - name: Build project
        run: npm run build

      // Netlify에 배포
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './dist'
          production-branch: master
          deploy-message: 'Deploy from GitHub Actions'
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1

```

### 📍 GitHub와 Slack 연동
- 배포 결과까지 자동화하여 알 수 있도록 Slack 알림 연동 완료 🧚
<img width="677" alt="image" src="https://github.com/TrainingDiary/training-diary-frontend/assets/109029407/6a157591-773e-4a14-8850-034d8e7c2382">
